// Generated by CoffeeScript 1.4.0
var app, appygram, assets, express, port, stylus;

express = require('express');

stylus = require('stylus');

assets = require('connect-assets');

appygram = require('appygram');

app = express();

app.use(assets());

app.use(express["static"](process.cwd() + '/public'));

app.set('view engine', 'jade');

app.use(app.router);

appygram.setApiKey('cb96a697cec9bb9c1a57db549bb3d1b00129a7af');

appygram.format = 'text';

app.use(appygram.errorHandler);

app.get('/', function(req, resp) {
  return resp.render('index');
});

app.get('/test_error', function(req, resp) {
  return require('test_appygram_message_handler_blah_blah');
});

port = process.env.PORT || process.env.VMC_APP_PORT || 3000;

app.listen(port, function() {
  return console.log("Listening on " + port + "\nPress CTRL-C to stop server.");
});
